#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

OMV_SABNZBD_APP_PATH="/opt/sabnzbd"
OMV_SABNZBD1_OLD_DATA_PATH="/home/sabnzbd/.sabnzbd"
OMV_SABNZBD2_OLD_DATA_PATH="/home/sabnzbd/.sabnzbd2"
OMV_SABNZBD1_DATA_PATH="/var/opt/sabnzbd"
OMV_SABNZBD2_DATA_PATH="/var/opt/sabnzbd2"
OMV_SABNZBD_USER="sabnzbd"
OMV_SABNZBD_GROUP="users"

case "$1" in
    configure)
        SERVICE_XPATH_NAME="sabnzbd"
        SERVICE_XPATH="/config/services/${SERVICE_XPATH_NAME}"

        if ! getent passwd sabnzbd >/dev/null 2>&1; then
            echo "Adding sabnzbd user..."
            adduser --quiet \
                    --system \
                    --ingroup $OMV_SABNZBD_GROUP \
                    --no-create-home \
                    --disabled-password \
                    $OMV_SABNZBD_USER
            insserv -d sabnzbd
        else
            echo "sabnzbd user already exists."
        fi

        if [ -e $OMV_SABNZBD1_OLD_DATA_PATH ]; then
            if [ ! -e "${OMV_SABNZBD1_DATA_PATH}/sabnzbd.ini" ]; then
                cp -Ra $OMV_SABNZBD1_OLD_DATA_PATH/* $OMV_SABNZBD1_DATA_PATH
                #rm -Rf OMV_SABNZBD1_OLD_DATA_PATH
            fi
        fi

        if [ -e $OMV_SABNZBD2_OLD_DATA_PATH ]; then
            if [ ! -e "${OMV_SABNZBD2_DATA_PATH}/sabnzbd.ini" ]; then
                mv $OMV_SABNZBD2_OLD_DATA_PATH $OMV_SABNZBD2_DATA_PATH
                chown $OMV_SABNZBD_USER:$OMV_SABNZBD_GROUP $OMV_SABNZBD2_DATA_PATH -R
            fi
        fi

        STABLE=`curl -s -L https://github.com/sabnzbd/sabnzbd/releases/latest | grep -m1 '\-src.tar.gz' | sed 's#.*SABnzbd-\(.*\)-.*#\1#'`

        if [ ${#STABLE} -gt 10 ]; then
            STABLE=`curl -s -L https://github.com/sabnzbd/sabnzbd/releases/latest | grep -m1 SABnzbd- | sed 's#.*SABnzbd-\(.*\)-.*#\1#'`
        fi

        if [ ${#STABLE} -gt 10 ]; then
            STABLE=`curl -s -L https://github.com/sabnzbd/sabnzbd/releases | grep -m1 SABnzbd- | sed 's#.*SABnzbd-\(.*\)-.*#\1#'`
        fi

        if [ ! -f /opt/SABnzbd/SABnzbd.py ]; then
            wget -q -nv https://github.com/sabnzbd/sabnzbd/releases/download/${STABLE}/SABnzbd-${STABLE}-src.tar.gz -O /tmp/sabnzbdplus.tar.gz > /dev/null 2>&1
            tar xzf /tmp/sabnzbdplus.tar.gz -C /tmp/
            cp -fRa /tmp/SABnzbd-${STABLE}/. /opt/SABnzbd/
            rm -fR /tmp/sabnzbdplus.tar.gz
            rm -fR /tmp/SABnzbd-${STABLE}
        fi

        if ! omv_config_exists "${SERVICE_XPATH}"; then
            echo "Initial configuration."
            omv_config_add_element "/config/services" "${SERVICE_XPATH_NAME}"
            omv_config_add_element "${SERVICE_XPATH}" "enable" "0"
            omv_config_add_element "${SERVICE_XPATH}" "newinstance" "0"
            omv_config_add_element "${SERVICE_XPATH}" "newinstenable" "0"
            omv_config_add_element "${SERVICE_XPATH}" "ssl" "0"
            omv_config_add_element "${SERVICE_XPATH}" "ppass" "0"
            omv_config_add_element "${SERVICE_XPATH}" "showtab" "0"
            omv_config_add_element "${SERVICE_XPATH}" "update" "0"
        fi

        if omv_config_exists "${SERVICE_XPATH}/mntentref"; then
            omv_config_delete "${SERVICE_XPATH}/mntentref"
        fi

        if omv_config_exists "${SERVICE_XPATH}/path"; then
            omv_config_delete "${SERVICE_XPATH}/path"
        fi

        if ! omv_config_exists "${SERVICE_XPATH}/beta"; then
            omv_config_add_element "${SERVICE_XPATH}" "beta" "0"
        fi


        chown $OMV_SABNZBD_USER:$OMV_SABNZBD_GROUP $OMV_SABNZBD_APP_PATH
        chown $OMV_SABNZBD_USER:$OMV_SABNZBD_GROUP $OMV_SABNZBD1_DATA_PATH -R
        chmod 775 $OMV_SABNZBD_APP_PATH -R

        # Activate package triggers. These triggers are only set during the
        # package installation.
        dpkg-trigger update-fixperms
        dpkg-trigger update-locale
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument" >&2
        exit 1
    ;;
esac

exit 0
