#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

case "$1" in
configure)
    if ! omv_config_exists "/config/services/sabnzbd"; then
        echo "Initial configuration."
        object="<enable>0</enable>"
        object="${object}<showtab>0</showtab>"
        omv_config_add_element "/config/services" "sabnzbd" "${object}" true
    fi

    if ! grep -q "^sabnzbd:" /etc/passwd; then
        echo "Adding sabnzbd user..."
        useradd --no-create-home --groups users --no-user-group --shell /usr/sbin/nologin sabnzbd
    else
        echo "sabnzbd user already exists."
    fi

    chown -R sabnzbd:users /opt/sabnzbd

    ;;
abort-upgrade|abort-remove|abort-deconfigure)
    ;;
*)
    echo "postinst called with unknown argument" >&2
    exit 1
    ;;
esac

exit 0
